### ISSUE TITLE
Presentation.SaveAs confusing PpSaveAsFileType

### ISSUE THREAD

**Issue by darkdragon-001** [OfficeDev/VBA-content#258]
In file `VBA/PowerPoint-VBA/articles/d70a678b-66ed-9dd6-5a5e-454cdf808784.md` (`Presentation.SaveAs`), the example at the button uses `ppSaveAsPowerPoint4` while the list of all possible `PpSaveAsFileType` does not have this entry.

It would also be helpful to have a short description what each of these constants means.

**Comment by darkdragon-001** [comment]
I found some more information at [https://msdn.microsoft.com/en-us/library/microsoft.office.interop.powerpoint.ppsaveasfiletype.aspx]().

But it is still not clear to me, which of these options is the `.ppt` and which one the `.pptx` format.

**Comment by laschultz** [comment]
darkdragon-001,
Thank you for brining this issue to our attention. Your contribution helps improve the documentation quality. I'll look into your issue and get back to you with a response.
Thanks,
Office Scale Team

**Comment by laschultz** [comment]
darkdragon-001,
I've included a link to the topic with the constant descriptions. Since we've moved to an open publishing environment, we now look to developers to help us keep the documentation up to date. In the future, feel free to make changes directly to the GitHub repo and submit a Pull Request.
Thanks,
Office Scale Team
