### ISSUE TITLE
VBA syntax for Word 2013

### ISSUE THREAD

**Issue by kasi1999999** [OfficeDev/VBA-content#289]
Hello,
I have problem with VBA code in Word 2013, when I open Developer Tools -> Visual Basic, Microsoft Visual Basic For Application 7.1.1049 opens. Where can I find the syntax manual for the VBA I can use here? Basic language structures like while (https://msdn.microsoft.com/en-en/library/zh1f56zs.aspx), the first sample is not working. Same for for cycle. Thanks a lot.
Stefan.

**Comment by sixareen** [comment]
Stefan: The problem is that you have found the documentation that applies to the .NET version of Visual Basic (VB.NET). In my experience, searching via e.g. Google or whatever will tend to lead you to the VB.NET documentation rather than the VBA documentation. VB.NET differs from VBA in many ways. For example, VB.NET has While...End While, but VBA has While...Wend.  You can find the VBA documentation for that particular language construct at https://msdn.microsoft.com/en-US/en-en/library/zh1f56zs.aspx . 

FWIW these GitHub pages used to have a useful set of Office VBA documentation with a useful ToC. However, looking around now, a lot of stuff appears to have been damaged. Perhaps I am looking in the wrong place.

**Comment by kasi1999999** [comment]
Hello sixareen,
thank you very much for explanation, why I am confused, that I need to look for VBA instead of VB.NET. Sori but link you provided is also for VB.NET, I see there While...End While statement. 

I googled and found this documentation https://msdn.microsoft.com/en-us/library/aa266320(v=vs.60).aspx.
It is pity, that the GitHub content concerning Office VBA documentation is missing, it would be great if it can be restored. 

I am disappointed by quality and structure of MS documentation in general.
Stefan

**Comment by sixareen** [comment]
Stefan: sorry about the wrong link. Mine should have been https://msdn.microsoft.com/en-us/library/office/gg264682.aspx . I'll try and fix my other post.
