### ISSUE TITLE
Document  Application.ScreenUpdating = True - this needs to be reset when opening/creating a new workbook

### ISSUE THREAD

**Issue by nodrogl** [OfficeDev/VBA-content#379]

**Comment by jacobmorehouse** [comment]
@nodrogl , is this a problem with the application functionality or with the documentation? I suspect you are referencing an application issue but haven't provided enough information to confidently make that determination. Could you elaborate?

**Comment by lindalu-MSFT** [comment]
@nodrogl Please open a new issue if you find any bugs in our documentation. Otherwise, if you need to ask questions about your code, you can try Stack Overflow. Often, the community of developers can answer your questions faster than we can! 

[Stack Overflow for VBA questions](https://stackoverflow.com/questions/tagged/vba)
[Stack Overflow for Word developer questions](https://stackoverflow.com/questions/tagged/ms-word)
