### ISSUE TITLE
Can't find project or library . help

### ISSUE THREAD

**Issue by Steviey** [OfficeDev/VBA-content#389]
Article "can-t-find-project-or-library.md" doesn't help, if you are in a Excel-crash-loop without references dialog.

**Comment by lindalu-MSFT** [comment]
@Steviey Have you tried Stack Overflow for your excel code questions? Often, the community can offer help for specific issues. Let us know if you see an actual but in our documentation, otherwise I'll take this as a suggestion and close for now. 

Try Stack Overflow tagged Excel: [https://stackoverflow.com/questions/tagged/excel](https://stackoverflow.com/questions/tagged/excel)

thanks, lindalu@microsoft.com
