### ISSUE TITLE
How to markdown HTML entities in files used within CHM files?

### ISSUE THREAD

**Issue by ThunderFrame** [OfficeDev/VBA-content#426]
Given a file like [ VBA-content/VBA/Language-Reference-VBA/articles/comparison-operators.md ](https://github.com/OfficeDev/VBA-content/blob/offline-docs/VBA/Language-Reference-VBA/articles/comparison-operators.md), which is presumable compiled into a CHM file...

The content has originally, or at some point, been marked up in HTML (eg. named escaped characters like `&lt;` for `<` instances, because the CHM file requires HTML content.

But *some* markdown has been applied to *some* HTML entities, meaning that the content is neither purely markdown nor purely compliant HTML:

```txt
|**&lt;= (** Less than or equal to)| _expression1_ <= _expression2_| _expression1_ > _expression2_| _expression1_ or _expression2_ = **Null**|
_expression2_ = **Null**|
```

Note the use of `&lt;` and subsequent use of `<=` later on the line.

What should we be targeting for the best markdown in such cases? My own view is that the file should be in pure compliant markdown (without regard to HTML entities), and that the process that converts the MD file into HTML, and subsequently packages those HTML files into the CHM should be doing the markdown to HTML encoding and conversions.

**Comment by lindalu-MSFT** [comment]
@ThunderFrame So sorry for the delayed response. This repo was orphaned until I adopted it a month or so ago and I'm only just catching up with the issues. YES, we absolutely agree. The markdown should only contain HTML if absolutely necessary to render, otherwise it should be pure markdown. We welcome any changes you can make if you find these typos in our content.
